- .eslintrc.json
- .gitignore
- .nycrc
- karma.conf.js
- lib/index.js
- package-lock.json
- package.json
- test/.eslintrc.json
- test/index-test.js
Fixes https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/1
> trivial API + tests + coverage

- .travis.yml
- README.md
> Build: Travis-CI support

- lib/datastore.js
- test/datastore-test.js
making sure a few more initialization paths are covered.
> Build: improve initialization tests

- README.md
Whoops, wasn't paying attention to the fact it included a branch name in the URL.
> fix URL typo

- .codecov.yml
- .travis.yml
- README.md
- karma.conf-base.js
- package-lock.json
- package.json
This ran locally OK (with `-t {token}`) and hopefully will kick off as expected when Travis finishes up here...
> Add codecov to replace coveralls

- README.md
Just minor nits to make the README similar to the lockbox-extension:
https://github.com/mozilla-lockbox/lockbox-extension/pull/63
> Tidy the readme

- jsdoc.conf.js
- lib/datastore.js
- lib/index.js
- lib/itemkeystore.js
- lib/localdatabase.js
- package-lock.json
- package.json
- test/datastore-test.js
- test/index-test.js
- test/itemkeystore-test.js
> Update: Persist items using IndexedDB

- test/datastore-test.js
Here's a 1st go at adding a test, please be brutal with your review and help me make this better (-:
> add a persistence test

- docs/lock-unlock.md
for https://github.com/mozilla-lockbox/lockbox-extension/issues/16 authored by @jimporter
Any final edits before publishing @linuxwolf @jimporter?
Related code changes at #30
> Docs: Add lock/unlock design documentation

- lib/datastore.js
- lib/itemkeystore.js
- test/datastore-test.js
- test/itemkeystore-test.js
The backend work to support mozilla-lockbox/lockbox-extension#137
> feature: reset a datastore

- lib/datastore.js
- lib/index.js
- test/datastore-test.js
This provides the datastore hooks for telemetry.
> feature: add support for metrics reporting

- README.md
- docs/index.md
to match https://github.com/mozilla-lockbox/lockbox-extension/pull/302
> Add links to overall Lockbox product/project website and docs

- .gitignore
- .npmignore
- .travis.yml
- docs/releases.md
> chore: release processes

- .npmignore
PREPARE TO BE AMAZED!
Fixes #84
> Add docs/ and CHANGELOG.md to .npmignore file

- lib/constants.js
- lib/datastore.js
- lib/itemkeystore.js
- lib/localdatabase.js
- test/datastore-test.js
- test/itemkeystore-test.js
- test/localdatabase-test.js
Resolves #78
Implements the required changes, plus a couple of placeholders.  The remainder is safer to accomplish when the tables start to be used.
> Update Local IndexedDB Schema

- .eslintrc.json
- lib/datastore.js
- lib/items.js
- package-lock.json
- test/datastore-test.js
- test/items-test.js
> Added `touch` method to set last_used property 

- package.json
> chore(package): update documentation to version 6.3.3

- lib/itemkeystore.js
- package.json
> Greenkeeper/eslint plugin jsdoc 3.7.0

- package-lock.json
- package.json
> chore(package): update webpack to version 4.14.0

- package-lock.json
- package.json
> chore(package): update karma-coverage-istanbul-reporter to version 2.0.1

- package-lock.json
- package.json
> chore(package): update documentation to version 8.0.0

- package-lock.json
- package.json
> Greenkeeper/webpack 4.19.1
